from pydantic import BaseModel, Field
from typing import List


class QueryRequest(BaseModel):
    question: str = Field(..., description="The user question about FastAPI documentation")


class QueryResponse(BaseModel):
    answer: str = Field(..., description="Grounded answer text generated by the LLM")
    sources: List[str] = Field(default_factory=list, description="List of source documentation filenames used")
